services:
  postgres-master:
    image: postgres:16-alpine
    container_name: onsite-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-master:/var/lib/postgresql/data
    networks:
      - onsite-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  pgpool:
    image: pgpool/pgpool:4.4.3
    container_name: onsite-pgpool
    ports:
      - ${DB_PORT}:5432
    depends_on:
       postgres-master:
        condition: service_healthy
    environment:
      PGPOOL_PARAMS_BACKEND_HOSTNAME0: postgres-master
      PGPOOL_PARAMS_BACKEND_PORT0: 5432
      PGPOOL_PARAMS_BACKEND_WEIGHT0: 1
      PGPOOL_PARAMS_BACKEND_FLAG0: ALWAYS_PRIMARY

      PGPOOL_PARAMS_ENABLE_POOL_HBA: 'off'
      PGPOOL_PARAMS_ALLOW_CLEAR_TEXT_FRONTEND_AUTH: 'on'

      PGPOOL_PARAMS_PCP_USER: ${PGPOOL_PCP_USER}
      PGPOOL_PARAMS_PCP_PASSWORD: ${PGPOOL_PCP_PASSWORD}

    networks:
      - onsite-net

  redis:
    image: redis:7-alpine
    container_name: onsite-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "$${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - onsite-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.31.2-alpine
    container_name: onsite-nginx 
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - onsite-net 
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.11"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-services:
    container_name: onsite-auth
    image: onsite/auth-service:local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      PGPOOL_PCP_USER: ${PGPOOL_PCP_USER}
      PGPOOL_PCP_PASSWORD: ${PGPOOL_PCP_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      NGINX_PORT: ${NGINX_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8001:8001
    networks:
      - onsite-net
    depends_on:
      postgres-master:
        condition: service_healthy
      pgpool:
        condition: service_started
      redis:
        condition: service_healthy
      nginx:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:8001/health"]
      timeout: 20s
      retries: 10
      interval: 30s

volumes:
  postgres-master:
  redis:
  nginx:

networks:
  onsite-net:
    driver: bridge